name: helo_world_workflow

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello_world
      - run: echo "hello world"
      - shell: bash
  goodbey:
    runs_on: ubuntu-latest
    steps:
      - name: godbey
      - run: echo "goddbey"
      - shell: bash

