name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use GitHub Secret
        run: echo ${{ secrets.YOUR_SECRET_NAME }}
